import random
print("Select a language/Выберите язык")
a = input('Eng=2/Рус=1:')
if a == '1':
    while True:
            b =[
        "Жизнь — это не то, что с тобой происходит, а то, как ты это воспринимаешь.",
        "Смысл жизни не в том, чтобы найти себя, а в том, чтобы создать себя.",
        "Иногда нужно заблудиться, чтобы найти себя.",
        "Жизнь начинается там, где заканчивается зона комфорта.",
        "Главное — не как быстро ты идешь, а в том ли ты направлении.",
        "Всё, что ты ищешь, ищет тебя.",
        "Не бойся медлить, бойся остановиться.",
        "Иногда самые невероятные путешествия — это те, что мы совершаем внутри себя.",
        "Ты — автор своей жизни. Не давайте никому в руки карандаш.",
        "Жизнь — это 10% того, что с нами происходит, и 90% того, как мы на это реагируем.",
        "Сложные дороги ведут к прекрасным местам.",
        "Падение — это часть пути, а не конец путешествия.",
        "Сравнивай себя не с другими, а с собой вчерашним.",
        "Если ты ждешь идеального момента, ты можешь ждать вечно.",
        "Лучший способ предсказать будущее — создать его.",
        "Живи так, чтобы люди, встретив тебя, стали счастливее.",
        "Счастье — это не пункт назначения, а способ путешествовать.",
        "Не ищи легких путей — ищи себя на сложных.",
        "Время, которое ты любишь потратить, потрачено не зря.",
        "Жизнь похожа на зеркало: она улыбается тебе, если ты смотришь на нее с улыбкой.",
        "Ты никогда не пересечешь океан, если не наберешься смелости потерять берег из виду.",
        "Начинать всегда стоит с того, что сеет сомнения.",
        "Самое важное в жизни — это не конечная цель, а путь к ней.",
        "Порой нужно молчать, чтобы услышать шепот своей души.",
        "Не позволяй шуму чужих мнений заглушить твой внутренний голос.",
        "Жизнь — это выбор. Ты либо создаешь ее, либо наблюдаешь.",
        "Настоящая жизнь происходит, когда ты выходишь за рамки своих страхов.",
        "Будь собой, все остальные роли уже заняты.",
        "Урок, который ты не выучил, жизнь будет преподавать снова и снова.",
        "Не существует карты, которая покажет тебе твой путь. Ты создаешь его, делая шаги.",


        "Любить — значит видеть в человеке то, чего не видят другие.",
        "Настоящая любовь не в том, чтобы не расставаться, а в том, чтобы всегда возвращаться.",
        "Сердце имеет причины, которых не знает разум.",
        "Любовь — это когда чужая боль становится твоей.",
        "Самый большой риск — не рисковать в любви.",
        "Любовь — это глагол. Чувства приходят и уходят, а действия остаются.",
        "Лучше быть одному, чем с кем попало.",
        "Не ищи человека, с которым будешь счастлива. Будь счастлива, и ты найдешь человека.",
        "Самый большой комплимент — когда тебя любят за то, что ты настоящий.",
        "Расстояние учит ценить моменты вместе.",
        "Иногда нужно отпустить, чтобы понять, было ли это твоим.",
        "Любовь — это не два человека, смотрящих друг на друга, а два человека, смотрящих в одном направлении.",
        "Самые важные слова в любви: \"Я здесь, с тобой\".",
        "Настоящая любовь не подавляет, а вдохновляет расти.",
        "Сердце разбивается не для того, чтобы остаться в осколках, а чтобы открыться шире.",
        "Любовь не в том, чтобы найти идеального человека, а в том, чтобы увидеть неидеального совершенно.",
        "Тишина между двумя людьми бывает красноречивее слов.",
        "Доверие строится годами, а разрушается за секунду.",
        "Самые крепкие связи рождаются не из совершенства, а из умения прощать несовершенство.",
        "Любить кого-то — значит видеть в нем ту магию, которую он в себе не видит.",
        "Если тебя любят — ты это чувствуешь. Не нужно гадать.",
        "Одиночество лучше, чем отношения, в которых ты одинок.",
        "Настоящая близость — это когда не страшно показать свои слабости.",
        "Любовь — это когда его счастье становится необходимым для твоего.",
        "Иногда нужно разойтись, чтобы найти дорогу друг к другу.",
        "Не меняйся ради любви. Найди ту, кто полюбит тебя за то, кто ты есть.",
        "Самые красивые истории пишутся не пером, а сердцем.",
        "Любовь не должна быть удобной. Она должна быть настоящей.",
        "Лучшее, что можно дать другому, — это пространство быть собой.",
        "Самая сильная любовь — та, что прошла через испытания.",


        "Ты сильнее, чем думаешь.",
        "Шторм делает дерево крепче.",
        "Иногда твои слезы — это вода, из которой растет твоя сила.",
        "То, что тебя не ломает, делает тебя сильнее.",
        "Кризис — это возможность роста, замаскированная под проблему.",
        "Ты можешь испытывать боль, но не позволяй ей управлять тобой.",
        "Самая темная ночь перед рассветом.",
        "Смелость — это не отсутствие страха, а понимание, что что-то важнее страха.",
        "Падать — это нормально. Вставать — обязательно.",
        "Когда тебе тяжело, просто помни: камень точит не сила, а постоянство.",
        "Ты пережил 100% своих худших дней. Ты справишься и с этим.",
        "Проблемы — это не остановки, а часть пути.",
        "Иногда нужно сломаться, чтобы собраться заново — правильно.",
        "Боль временна. Уроки — навсегда.",
        "Не позволяй тяжелому дню убедить тебя, что у тебя тяжелая жизнь.",
        "Ты не жертва обстоятельств, ты их свидетель. И ты можешь изменить сценарий.",
        "В каждом из нас есть тихая сила, которая ждет, когда ее позовут в бой.",
        "Выдержка — это когда ты улыбаешься, хотя хочется плакать.",
        "Самые сильные люди — не те, кто всегда побеждает, а те, кто не сдается, проигрывая.",
        "Шрамы — это следы того, что ты выжил.",
        "Сила приходит не от физических возможностей, а от несгибаемой воли.",
        "Дно — отличная точка для отталкивания.",
        "Не бойся начинать сначала. Это шанс построить все лучше.",
        "Иногда нужно замедлиться, чтобы восстановить силы для прыжка.",
        "Плакать — не значит быть слабым. Значит, ты был сильным слишком долго.",
        "Самое большое препятствие — это страх в твоей голове.",
        "Испытания не приходят, чтобы сломить тебя. Они приходят, чтобы раскрыть тебя.",
        "Выдержать можно все, если видишь в этом смысл.",
        "Даже в самой горькой полыни есть капля меда. Найди ее.",
        "Не ищи легких путей. Ищи то, ради чего стоит идти по трудным.",


        "Мечтай так, как будто будешь жить вечно. Живи так, как будто умрешь сегодня.",
        "Если мечта не пугает, она слишком мала.",
        "Будущее принадлежит тем, кто верит в красоту своей мечты.",
        "Цель — это не просто пункт назначения, а направление движения.",
        "Не откладывай свою мечту на \"когда-нибудь\". \"Когда-нибудь\" — это не день недели.",
        "Мечта становится реальностью, когда к ней добавляются действие и срок.",
        "Стреляй в луну. Даже если промахнешься, окажешься среди звезд.",
        "Твои мечты не должны умещать тебя. Ты должен вырасти до своих мечтаний.",
        "Самый большой риск — не рисковать ради мечты.",
        "Мечты — это семена. Посади их, поливай действиями.",
        "Не позволяй шуму чужих мнений заглушить твой внутренний голос.",
        "Дорога к мечте вымощена дисциплиной.",
        "Если ты можешь это вообразить, ты можешь этого достичь.",
        "Мечта — это не то, что ты видишь во сне, а то, что не дает тебе уснуть.",
        "Начни с того, что необходимо; затем сделай то, что возможно; и внезапно ты совершишь невозможное.",
        "Твоя цель должна быть достаточно большой, чтобы пугать, и достаточно четкой, чтобы вести.",
        "Мечты не работают, пока не работаешь ты.",
        "Самый долгий путь начинается с одного шага.",
        "Не жди идеального момента. Возьми момент и сделай его идеальным.",
        "Успех — это движение от неудачи к неудаче без потери энтузиазма.",
        "Будущее наступает не само по себе. Мы создаем его.",
        "Тот, кто не смотрит вперед, оказывается позади.",
        "Твои сегодняшние действия определяют твое завтра.",
        "Если ты не знаешь, куда плыть, никакой ветер не будет попутным.",
        "Лучшее время что-то посадить было 20 лет назад. Следующий лучший момент — сейчас.",
        "Мечты сбываются у тех, кто не спит.",
        "Не рассказывай о своих планах. Просто тихо делай и удивляй всех результатом.",
        "Тот, кто хочет сдвинуть мир, пусть сначала сдвинет себя.",
        "Цель без плана — это просто желание.",
        "Верь в свою мечту, даже когда никто не верит.",
        "Время не ждет, но оно лечит.",
        "Единственная постоянная в жизни — это изменение.",
        "Не трать время, жалея о прошлом, или беспокоясь о будущем. Живи настоящим.",
        "Вчера — это история, завтра — загадка, сегодня — подарок. Поэтому его и называют \"настоящим\".",
        "Время, как река, уносит все, что не укоренилось.",
        "Изменения болезненны, но они единственный путь к росту.",
        "Иногда нужно отпустить старое, чтобы освободить место для нового.",
        "Лучшее, что можно сделать с прошлым, — это извлечь из него урок и идти дальше.",
        "Время — самый честный судья.",
        "Не говори \"у меня нет времени\". У тебя ровно столько же времени, сколько было у великих людей.",
        "Прошлое нельзя изменить, но будущее — в твоих руках.",
        "Моменты уходят быстрее, чем мы успеваем их осознать.",
        "Иногда шаг назад — это часть движения вперед.",
        "Жизнь измеряется не количеством вдохов, а количеством моментов, от которых захватывает дух.",
        "Время — это ткань, из которой состоит жизнь.",
        "Не откладывай на завтра то, что сделает твое сегодня лучше.",
        "Изменения начинаются тогда, когда ты делаешь то, что раньше не делал.",
        "Самые важные вещи в жизни не вещи, а моменты.",
        "С годами ты понимаешь, что меньше значит больше, а тишина говорит громче слов.",
        "Сегодня — первый день оставшейся жизни.",
        "Рост требует временного дискомфорта.",
        "Время не любит, когда его тратят впустую.",
        "Будущее уже здесь — оно просто неравномерно распределено.",
        "Не бойся медленных изменений. Бойся стоять на месте.",
        "Иногда потеряться во времени — значит найти себя.",
        "Каждый день — чистый лист. Что ты на нем напишешь?",
        "Прошлое — это пролог.",
        "Настоящее — это точка, где встречаются планы прошлого и мечты о будущем.",
        "Время — лучший учитель, но, к сожалению, оно убивает всех своих учеников.",
        "Перемены неизбежны. Рост — это выбор.",
        "Спокойствие — это не место, где нет шума, проблем или тяжелой работы. Это место внутри, куда можно прийти, несмотря на хаос вокруг.",
        "Иногда самое мудрое слово — это молчание.",
        "Знание говорит, мудрость слушает.",
        "Ты не можешь успокоить бурю, но можешь научиться танцевать под дождем.",
        "Мудрость приходит с годами, но иногда годы приходят одни.",
        "Самый большой враг внутреннего мира — ожидания.",
        "Будь добр к себе в мыслях. Ты проводишь с собой 24/7.",
        "Мудрость — это видеть невидимое, чувствовать неощутимое и достигать невозможного.",
        "Тишина — это язык Бога, все остальное — плохой перевод.",
        "Главное — не быть правым, а быть в мире с собой.",
        "Ответы приходят, когда ты перестаешь искать их снаружи и начинаешь слушать внутри.",
        "Чем меньше ты нуждаешься в одобрении, тем ближе ты к своей силе.",
        "Мудрость начинается с удивления.",
        "Не ищи счастья вовне. Оно всегда было внутри тебя.",
        "Позволь вещам идти своим чередом. Не все требует твоей реакции.",
        "Чем больше ты знаешь, тем меньше тебе нужно доказывать.",
        "Интуиция — это мудрость, говорящая шепотом.",
        "Будь как вода: гибкой, принимающей форму сосуда, но способной точить камень.",
        "Настоящая сила — в мягкости, которую не сломать.",
        "Мир приходит не от отсутствия проблем, а от умения с ними жить.",
        "Иногда отпустить — это акт большей силы, чем удержать.",
        "Не позволяй уму быть громче сердца.",
        "Мудрость — это понимание, что солнце каждый день восходит заново.",
        "Счастье — это когда то, что ты думаешь, говоришь и делаешь, находится в гармонии.",
        "Самый долгий путь — путь к самому себе.",
        "Будь внимателен к своим мыслям: они — начало поступков.",
        "Умиротворение — это не когда все идеально, а когда ты принимаешь несовершенство.",
        "Знать много — не значит быть мудрым. Мудрость — в применении знаний.",
        "Найди покой в принятии того, что ты не можешь изменить.",
        "Чаще смотри на небо, чтобы помнить, как ты мал, и на свой путь, чтобы помнить, как ты велик.",
        "Творчество — это позволить себе делать ошибки. Искусство — это знать, какие из них оставить.",
        "Вдохновение существует, но оно должно застать тебя за работой.",
        "Не жди вдохновения. Иди за ним с дубинкой.",
        "Творить — значит дышать. Нельзя этим не заниматься.",
        "Каждый ребенок — художник. Проблема в том, как остаться художником, повзрослев.",
        "Искусство смывает пыль повседневности с души.",
        "Сделай шаг, и дорога появится сама.",
        "Творчество — это интеллект, который получает удовольствие.",
        "Самые яркие краски рождаются из внутренней тьмы.",
        "Не бойся совершенства. Тебе его никогда не достичь.",
        "Твоя уникальность — это твоя сила. Не стирай ее.",
        "Пиши, рисуй, пой, танцуй так, как будто никто не смотрит. Потому что в моменте творения важно только твое сердце.",
        "В каждом из нас спит гений. Разбуди своего.",
        "Творческий кризис — это не тупик, а поворот.",
        "Идеи приходят, когда ты занят делом, а не размышлениями о деле.",
        "Создавай не для лайков, а для того, чтобы оставить след в своей душе.",
        "Рутина — враг творчества. Новизна — его лучший друг.",
        "Самый страшный враг творчества — здравый смысл.",
        "Творить — значит говорить \"да\" жизни.",
        "Пустота — это пространство, которое ждет, чтобы его заполнили смыслом. Начни."]
            print(random.choice(b))
            input('Для получения новой цитаты нажмите Enter')
if a == '2':
    while True:
        c = [
            "Life is not what happens to you, but how you perceive it.",
            "The meaning of life is not to find yourself, but to create yourself.",
            "Sometimes you need to get lost to find yourself.",
            "Life begins where your comfort zone ends.",
            "It's not about how fast you go, but whether you're going in the right direction.",
            "Everything you seek is seeking you.",
            "Don't be afraid of going slowly, be afraid of standing still.",
            "Sometimes the most incredible journeys are the ones we take within ourselves.",
            "You are the author of your life. Don't give anyone else the pencil.",
            "Life is 10% what happens to us and 90% how we react to it.",
            "Difficult roads lead to beautiful destinations.",
            "Falling is part of the journey, not the end of the travel.",
            "Compare yourself not to others, but to who you were yesterday.",
            "If you wait for the perfect moment, you might wait forever.",
            "The best way to predict the future is to create it.",
            "Live so that people become happier having met you.",
            "Happiness is not a destination, but a way of traveling.",
            "Don't look for easy ways—look for yourself on the difficult ones.",
            "Time you enjoy wasting is not wasted time.",
            "Life is like a mirror: it smiles at you if you look at it with a smile.",
            "You can never cross the ocean until you have the courage to lose sight of the shore.",
            "Always start with what creates doubt.",
            "The most important thing in life is not the final goal, but the path to it.",
            "Sometimes you need to be silent to hear the whisper of your soul.",
            "Don't let the noise of others' opinions drown out your own inner voice.",
            "Life is a choice. You either create it or observe it.",
            "Real life happens when you step beyond your fears.",
            "Be yourself; everyone else is already taken.",
            "The lesson you don't learn, life will teach you again and again.",
            "There is no map that will show you your path. You create it by taking steps.",
            "To love is to see in a person what others do not see.",
            "True love is not about never parting, but about always returning.",
            "The heart has its reasons which reason knows not.",
            "Love is when someone else's pain becomes your own.",
            "The biggest risk is not risking in love.",
            "Love is a verb. Feelings come and go, but actions remain.",
            "Better to be alone than with just anyone.",
            "Don't look for someone to be happy with. Be happy, and you'll find someone.",
            "The greatest compliment is being loved for who you truly are.",
            "Distance teaches you to value the moments together.",
            "Sometimes you need to let go to understand if it was yours.",
            "Love is not two people looking at each other, but two people looking in the same direction.",
            "The most important words in love: 'I am here with you.'",
            "True love does not suppress, but inspires growth.",
            "A heart breaks not to remain in pieces, but to open wider.",
            "Love is not about finding the perfect person, but about seeing an imperfect person perfectly.",
            "The silence between two people can be more eloquent than words.",
            "Trust is built over years and destroyed in seconds.",
            "The strongest bonds are born not from perfection, but from the ability to forgive imperfection.",
            "To love someone is to see the magic in them that they don't see in themselves.",
            "If you are loved—you feel it. No need to guess.",
            "Loneliness is better than a relationship where you are lonely.",
            "True intimacy is when you're not afraid to show your weaknesses.",
            "Love is when their happiness becomes necessary for yours.",
            "Sometimes you need to part ways to find the road back to each other.",
            "Don't change for love. Find someone who loves you for who you are.",
            "The most beautiful stories are written not with a pen, but with the heart.",
            "Love shouldn't be convenient. It should be real.",
            "The best thing you can give another is the space to be themselves.",
            "The strongest love is the one that has survived trials.",
            "You are stronger than you think.",
            "The storm makes the tree stronger.",
            "Sometimes your tears are the water from which your strength grows.",
            "What doesn't break you makes you stronger.",
            "A crisis is a growth opportunity disguised as a problem.",
            "You may experience pain, but don't let it control you.",
            "The darkest night is before the dawn.",
            "Courage is not the absence of fear, but the understanding that something is more important than fear.",
            "It's okay to fall. Getting up is mandatory.",
            "When times are tough, remember: it's not strength but persistence that wears down a stone.",
            "You have survived 100% of your worst days. You will survive this too.",
            "Problems are not stops, but part of the journey.",
            "Sometimes you need to break apart to reassemble correctly.",
            "Pain is temporary. Lessons are forever.",
            "Don't let a bad day convince you that you have a bad life.",
            "You are not a victim of circumstances; you are their witness. And you can change the script.",
            "Each of us has a quiet strength waiting to be called into battle.",
            "Endurance is when you smile even though you want to cry.",
            "The strongest people are not those who always win, but those who don't give up when they lose.",
            "Scars are traces that you survived.",
            "Strength comes not from physical capacity, but from an indomitable will.",
            "Rock bottom is a great place to push off from.",
            "Don't be afraid to start over. It's a chance to build everything better.",
            "Sometimes you need to slow down to regain strength for a leap.",
            "Crying doesn't mean you're weak. It means you've been strong for too long.",
            "The biggest obstacle is the fear in your head.",
            "Trials don't come to break you. They come to reveal you.",
            "You can endure anything if you see meaning in it.",
            "Even in the bitterest wormwood, there is a drop of honey. Find it.",
            "Don't look for easy paths. Look for what's worth walking the hard ones for.",
            "Dream as if you'll live forever. Live as if you'll die today.",
            "If your dreams don't scare you, they are too small.",
            "The future belongs to those who believe in the beauty of their dreams.",
            "A goal is not just a destination, but a direction.",
            "Don't postpone your dream for 'someday.' 'Someday' is not a day of the week.",
            "A dream becomes reality when you add action and a deadline.",
            "Shoot for the moon. Even if you miss, you'll land among the stars.",
            "Your dreams shouldn't fit you. You should grow to fit your dreams.",
            "The biggest risk is not taking a risk for your dream.",
            "Dreams are seeds. Plant them, water them with actions.",
            "Don't let the noise of others' opinions drown out your own inner voice.",
            "The road to your dreams is paved with discipline.",
            "If you can imagine it, you can achieve it.",
            "A dream is not what you see in your sleep, but what keeps you from sleeping.",
            "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
            "Your goal should be big enough to scare you and clear enough to guide you.",
            "Dreams don't work unless you do.",
            "The longest journey begins with a single step.",
            "Don't wait for the perfect moment. Take the moment and make it perfect.",
            "Success is moving from failure to failure without loss of enthusiasm.",
            "The future doesn't just happen. We create it.",
            "Those who don't look ahead find themselves left behind.",
            "Your actions today determine your tomorrow.",
            "If you don't know where you're sailing, no wind will be favorable.",
            "The best time to plant a tree was 20 years ago. The second best time is now.",
            "Dreams come true for those who stay awake.",
            "Don't talk about your plans. Just quietly do them and surprise everyone with the result.",
            "He who wants to move the world must first move himself.",
            "A goal without a plan is just a wish.",
            "Believe in your dream even when no one else does.",
            "Time doesn't wait, but it heals.",
            "The only constant in life is change.",
            "Don't waste time regretting the past or worrying about the future. Live in the present.",
            "Yesterday is history, tomorrow is a mystery, today is a gift. That's why it's called the present.",
            "Time, like a river, carries away everything that hasn't taken root.",
            "Change is painful, but it's the only path to growth.",
            "Sometimes you need to let go of the old to make room for the new.",
            "The best thing you can do with the past is learn from it and move on.",
            "Time is the most honest judge.",
            "Don't say 'I don't have time.' You have exactly the same amount of time as great people did.",
            "The past cannot be changed, but the future is in your hands.",
            "Moments pass faster than we can realize them.",
            "Sometimes a step back is part of moving forward.",
            "Life is measured not by the number of breaths we take, but by the moments that take our breath away.",
            "Time is the fabric from which life is made.",
            "Don't put off until tomorrow what can make your today better.",
            "Change begins when you start doing what you haven't done before.",
            "The most important things in life aren't things, but moments.",
            "With age, you realize that less is more and silence speaks louder than words.",
            "Today is the first day of the rest of your life.",
            "Growth requires temporary discomfort.",
            "Time doesn't like to be wasted.",
            "The future is already here—it's just not evenly distributed.",
            "Don't fear slow change. Fear standing still.",
            "Sometimes getting lost in time means finding yourself.",
            "Every day is a blank page. What will you write on it?",
            "The past is prologue.",
            "The present is the point where the plans of the past and the dreams of the future meet.",
            "Time is the best teacher, but unfortunately, it kills all its students.",
            "Change is inevitable. Growth is a choice.",
            "Peace is not a place without noise, trouble, or hard work. It is a place within that you can come to despite the chaos around you.",
            "Sometimes the wisest word is silence.",
            "Knowledge speaks, wisdom listens.",
            "You can't calm the storm, but you can learn to dance in the rain.",
            "Wisdom comes with years, but sometimes years come alone.",
            "The biggest enemy of inner peace is expectations.",
            "Be kind to yourself in your thoughts. You spend 24/7 with yourself.",
            "Wisdom is seeing the invisible, feeling the intangible, and achieving the impossible.",
            "Silence is the language of God; all else is poor translation.",
            "The main thing is not to be right, but to be at peace with yourself.",
            "Answers come when you stop searching for them outside and start listening within.",
            "The less you need approval, the closer you are to your power.",
            "Wisdom begins in wonder.",
            "Don't seek happiness outside. It has always been within you.",
            "Let things take their course. Not everything requires your reaction.",
            "The more you know, the less you need to prove.",
            "Intuition is wisdom speaking in a whisper.",
            "Be like water: flexible, taking the shape of the container, yet capable of wearing down stone.",
            "True strength lies in a softness that cannot be broken.",
            "Peace comes not from the absence of problems, but from the ability to live with them.",
            "Sometimes letting go is an act of greater strength than holding on.",
            "Don't let the mind be louder than the heart.",
            "Wisdom is understanding that the sun rises anew every day.",
            "Happiness is when what you think, say, and do are in harmony.",
            "The longest journey is the journey to yourself.",
            "Be mindful of your thoughts: they are the beginning of actions.",
            "Peace is not when everything is perfect, but when you accept imperfection.",
            "Knowing a lot doesn't make you wise. Wisdom lies in applying knowledge.",
            "Find peace in accepting what you cannot change.",
            "Look at the sky more often to remember how small you are, and at your path to remember how great you are.",
            "Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.",
            "Inspiration exists, but it has to find you working.",
            "Don't wait for inspiration. Chase it with a club.",
            "To create is to breathe. You can't not do it.",
            "Every child is an artist. The problem is how to remain an artist once we grow up.",
            "Art washes away from the soul the dust of everyday life.",
            "Take a step, and the road will appear.",
            "Creativity is intelligence having fun.",
            "The brightest colors are born from inner darkness.",
            "Don't be afraid of perfection. You'll never achieve it.",
            "Your uniqueness is your power. Don't erase it.",
            "Write, draw, sing, dance as if no one is watching. Because in the moment of creation, only your heart matters.",
            "There is a genius sleeping in each of us. Wake yours up.",
            "A creative block is not a dead end, but a turn.",
            "Ideas come when you are busy doing the work, not thinking about it.",
            "Create not for likes, but to leave a mark on your soul.",
            "Routine is the enemy of creativity. Novelty is its best friend.",
            "The most terrible enemy of creativity is common sense.",
            "To create is to say 'yes' to life.",
            "Emptiness is the space waiting to be filled with meaning. Begin."
        ]
        print(random.choice(c))
        input('To get a new quote, press Enter')



